### ISSUE TITLE
A question about spline_creator.py

### ISSUE THREAD

**Issue by cedricgsh** [karstenBehrendt/unsupervised_llamas#12]
Thanks for providing this great lane detection dataset. I have a question about your `spline_creator.py` file.
I want to visualize your spline annotations that generates by `spline_creator.py` file. However somes lanes lose its original shape, an severe instance showing in the picture.  
The path of this picture is `/llamas/color_images/train/images-2014-12-18-14-17-05/1418941044_0400918000_color_rect.png`. 
So could you fix these problems? 
@karstenBehrendt @lucastabelini 
![image](https://user-images.githubusercontent.com/33807572/115240593-7a872700-a152-11eb-8840-d6008e592c63.png)

**Comment by karstenBehrendt** [comment]
@cedricgsh Sorry about the late reply :/

I am sorry, there are images where the lane matching didn't work correctly. Therefore markers from one lane are connected to markers from another.

Since we couldn't publish the raw data, we won't be able to fix this. We could create a file that stores annotations which should be excluded.
